### ISSUE TITLE
Cannot startup v2ray service due to wrong CMD in Dockerfile

### ISSUE THREAD

**Issue by mia0x75** [zydou/GFW#3]
Error log from docker container:
```
[2K1Panel-localv2ray-cEBN  | Usage of /usr/bin/v2ray:
[2K1Panel-localv2ray-cEBN  | flag provided but not defined: -config
```

From Dockerfile we can see the startup CMD
```
CMD [ "/usr/bin/v2ray", "-config", "/etc/v2ray/config.json" ]
```

From v2ray [official document](https://www.v2ray.com/chapter_00/command.html), V2Ray has the following commandline parameters:
```
v2ray [-version] [-test] [-config=config.json] [-format=json]
```

so the corrent CMD should be as listed below
```
CMD [ "/usr/bin/v2ray", "run", "-config=/etc/v2ray/config.json" ]
```

After I add the following line into docker-compose.yml, the container runs normally.
```
command: "/usr/bin/v2ray run -config=/etc/v2ray/config.json"
```

**Comment by zydou** [comment]
Thank you for your reminder. The syntax `CMD [ "/usr/bin/v2ray", "-config", "/etc/v2ray/config.json" ]` is suitable for the `v2ray v4.x` version, while the syntax you referred to is intended for the new `v5.x` version. I will fix it after the vacation.
